default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

docker: &docker
  <<: *default
  host: <%= ENV['BRANCHING_DEMO_HOST'] %>
  username: <%= ENV['BRANCHING_DEMO_DATABASE_USERNAME'] %>
  password: <%= ENV['BRANCHING_DEMO_DATABASE_PASSWORD'] %>

development:
  <<: *docker
  database: branching_demo_development

test:
  <<: *docker
  database: branching_demo_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
